name: Update Blog

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-blog:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Blog Repo
        uses: actions/checkout@v4
        with:
          repository: Gyangu/blog
          token: ${{ secrets.BLOG_TOKEN }}
          path: blog
          
      - name: Initialize Submodule
        run: |
          cd blog
          git submodule update --init --recursive
        
      - name: Update Submodule
        run: |
          cd blog
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git submodule update --remote source
          git add source
          git diff --staged --quiet || git commit -m "Update obsidian notes"
          git push origin master
